require 'calculate/calculator'
require 'calculate/application'
require 'calculate/parser'
require 'calculate/add_command'
require 'calculate/sub_command'
require 'calculate/mul_command'
require 'calculate/sqr_command'
require 'calculate/sqrt_command'
require 'calculate/cube_command'
require 'calculate/cubert_command'
require 'calculate/abs_command'
require 'calculate/neg_command'
require 'calculate/div_command'
require 'calculate/cancel_command'
require 'calculate/repeat_command'

